Repository Lussebullen/DD2480_CI, pull requests merged in 2024-02, with the labels that each got.

#6 docs/ Add commit convention to README file
  README.md
Labels: documentation, good first issue

#21 feat/ Implemented the display of logs - handling of displaying both all logs and the individual logs
  ci/src/main/java/group17/ci/Router.java
  ci/src/main/resources/logs/demo.json
  ci/src/main/resources/logs/demo2.json
Labels: enhancement

#9 feat/ Added start script
  start.sh
Labels: enhancement

#43 fix/ CI Server no longer cares about branches other than "assessment"
  ci/src/main/java/group17/ci/Router.java
Labels: bug

#38 docs/ add Essence analysis to README
  README.md
Labels: documentation
